Pjw 3479 events
poached/sails-dynamodb pull request #1
Opened 2018-11-06 22:29 UTC by jcowley

2018-11-09 05:08 UTC, mossymaker requested changes
Minor issue, but could probably get by as-is.

2018-11-09 05:08 UTC, mossymaker commented on index.js
> +            adapter._getPrimaryKeys(collectionName).map(key => {
Since the return value isn't used, would it make more sense to use a _forEach_?

2018-11-12 23:03 UTC, jcowley commented
updated

2018-11-13 20:35 UTC, mossymaker approved these changes

2018-11-13 23:13 UTC, merged